### PR TITLE
Added EventEmitter

### PR DESCRIPTION
**Pull request by alex-alex**

### CODE REVIEW

**Comment by paulofaria** [comment]
Do you think we could add some default event emitters?

**Comment by alex-alex** [comment]
I think this doesn't belong to Core

**Comment by Danappelxx** [comment]
You should mark the `EventListener` and `EventEmitter` classes final.

**Comment by alex-alex** [comment]
Thanks @Danappelxx

**Comment by paulofaria** [comment]
Hmm, maybe you're right, but maybe some parts of the framework could take advantage of this. I guess it's ok to add them later when/if needed. Awesome work Alex.

**Comment by paulofaria** [comment]
I'm thinking `Stream` and `EventEmitter` are very similar.. Maybe `Stream` could be deprecated in favour of a `DataEventEmitter`.

**Comment by alex-alex** [comment]
That could work, we wouldn't probably need `pipe()` then, but we should defintiely leave `Stream` protocol, it's used by `SSL`.

**Comment by paulofaria** [comment]
You mean leave `Stream` for now, until we update `SSL` or forever? Is there anything `SSL` needs that a `DataEventEmitter` wouldn't provide?

**Comment by paulofaria** [comment]
wow I forgot to merge this. sorry! (:

**Pull request merged**
