### PR TITLE
Added File

### PR DESCRIPTION
**Pull request by alex-alex**

### CODE REVIEW

**Comment by paulofaria** [comment]
I think `File` should be a class with:
- Initializer that receives `path` and some flags and opens the file
- Deinitializer that closes the file
- Instance method `close()` to close the file before `deinit` if needed.
- Instance method `read(length: Int)` that reads `length` bytes. 
- Instance method `read()` that reads till EOF.
- Instance method `write(data: Data)` that writes data.

What do you think?

**Comment by alex-alex** [comment]
I agree. Better now?

**Comment by paulofaria** [comment]
Yeah man!! You're awesome! so fast.. haha

**Comment by paulofaria** [comment]
merge it! (:

**Pull request merged**
